DECLARE @ID_USU_ADMIN INT = (SELECT C.CLIID FROM CLIENTE C WHERE C.CLIUSULOGINID = 2)

-- CRIAR ACERTO DE ESTOQUE
INSERT INTO PRODUTOACERTOESTOQUE (
  EMPID,
  PAEVEDID,
  PAEVEDIDSAIDA,
  PAESTATUS,
  PAEUSUID,
  PAEDATAOCORRENCIA,
  PAEOBS
) 
SELECT 
  1                             AS 'EMPID',
  NULL                          AS 'PAEVEDID',
  NULL                          AS 'PAEVEDIDSAIDA',
  'A'                           AS 'PAESTATUS',
  @ID_USU_ADMIN                 AS 'PAEUSUID',
  CAST(GETDATE() AS DATETIME)   AS 'PAEDATAOCORRENCIA',
  'MAXDATA SISTEMA - MIGRACAO'  AS 'PAEOBS'
GO



DECLARE @ID_ACERTO_ESTOQUE INT = (SELECT MAX(PAE.PAEID) FROM PRODUTOACERTOESTOQUE PAE)

-- INSERIR ITENS NO ACERTO DE ESTOQUE
INSERT INTO PRODUTOACERTOESTOQUEITEM (
  PAIPAEID, 
  PAIPROID, 
  PAIPROESTOQUE, 
  PAIQTDINF, 
  PAILOTE, 
  PAILOTEESTOQUE
)
SELECT 
  @ID_ACERTO_ESTOQUE      AS 'PAIPAEID', 
  P.PROID                 AS 'PAIPROID', 
  0                       AS 'PAIPROESTOQUE', 
  P.PROESTOQUEATUAL   AS 'PAIQTDINF',
  'X'                     AS 'PAILOTE',
  0                       AS 'PAILOTEESTOQUE'
FROM PRODUTO_empresa P 
WHERE P.PROESTOQUEATUAL > 0
and p.EMPID =  -- perguntar para o usuario qual o id da empresa destino 
GO